apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-test
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:test
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 14.1.0 # We will move new versions of the chart into test by updating this field
    helm:
      parameters:
      - name: image.repository # We will move new versions of the image into test by updating this field
        value: 9673483686/some-nginx
      - name: image.registry
        value: ""          
      - name: image.tag # We will move new versions of the image into test by updating this field
        value: 0.0.5        
      - name: service.type
        value: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-uat
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:uat
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 14.1.0 # We will move new versions of the chart into stage by updating this field
    helm:
      parameters:
      - name: image.registry
        value: ""          
      - name: image.repository # We will move new versions of the image into test by updating this field
        value: 9673483686/some-nginx
      - name: image.tag # We will move new versions of the image into test by updating this field
        value: 0.0.5  
      - name: service.type
        value: ClusterIP
  destination:
    server: https://host.docker.internal:61922
    namespace: kargo-demo-uat
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:prod
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 14.1.0 # We will move new versions of the chart into prod by updating this field
    helm:    
      parameters:
      - name: image.repository # We will move new versions of the image into test by updating this field
        value: 9673483686/some-nginx
      - name: image.registry
        value: ""  
      - name: image.tag # We will move new versions of the image into test by updating this field
        value: 0.0.5  
      - name: service.type
        value: ClusterIP
  destination:
    server: https://host.docker.internal:61948
    namespace: kargo-demo-prod
