apiVersion: v1
kind: Namespace
metadata:
  name: kargo-helm-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-helm-uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-helm-prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-helm-test
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-helm:test
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 14.1.0 # We will move new versions of the chart into test by updating this field
    helm:
      parameters:
      - name: service.type
        value: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-helm-test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-helm-uat
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-helm:uat
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 14.1.0 # We will move new versions of the chart into stage by updating this field
    helm:
      parameters:
      - name: service.type
        value: ClusterIP
  destination:
    server: https://host.docker.internal:61922
    namespace: kargo-helm-uat
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-helm-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-helm:prod
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 14.1.0 # We will move new versions of the chart into prod by updating this field
    helm:
      parameters:
      - name: service.type
        value: ClusterIP
  destination:
    server: https://host.docker.internal:61948
    namespace: kargo-helm-test
